const yesBtn = document.querySelector('#yesBtn');

yesBtn.addEventListener('click',function () {
    alert('TE AMO COMO NO TIENES IDEA MI NENA PRECIOSA​❤️SOS TODO LO QUE SIEMPRE HABIA QUERIDO​❤️SOS PERFECTAA!!​❤️Y ERES Y SIEMPRE SERAS EL AMOR DE MI VIDA!​❤️Y MI MAYOR SUEÑO ES QUE NOSOTROS 2 TENGAMOS UN FUTUROO​❤️ DE IMAGINARLO YA ME PONGO MUYY FELIZ​❤️ESPERO QUE SIEMPRE SIGAMOS ASI CON LA ACTITUD DE SIEMPRE RESOLVER NUESTROS PROBLEMAS E INDIFERENCIAS​❤️SE QUE ESTO NO ES MUCHO YA QUE NO PUEDO ESTAR CONTIGO FISICAMENTE​❤️PERO YA FALTA MUY POQUITO PARA VERNOS Y ESTAR JUNTITOS Y HACER MUCHAS BOLUDECES​❤️TE AMOOOO DEMASIADOOO!!​❤️GRACIAS POR AYUDARME EN MIS PROBLEMAS Y DARME TU APOYO SIEMPRE​❤️Y MEJORAREMOS JUNTOS PARA TENER UNA RELACION ESTABLE Y ESTAR BIEN NOSOTROS DOS JUNTITOS​❤️ESTOY PNXNDEJX POR VOS Y NO LO PUEDO NEGARR​❤️ME HACES MUYYY PERO QUE MUYYY MUYYY FELIZZZ​❤️TE AMOOOOOOO Y GRACIAS POR APARECERTE EN MI VIDAAA​❤️​')
});

const noBtn = document.querySelector('#noBtn');

noBtn.addEventListener('mouseover', function () {
    const randomX = parseInt(Math.random()*100);
    const randomY = parseInt(Math.random()*100);
    noBtn.style.setProperty('top',randomY+'%');
    noBtn.style.setProperty('left',randomX+'%');
    noBtn.style.setProperty('transform',`translate(-${randomX}%,-${randomY}%)`);
})